import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "sonner";

import "./globals.css";

import CartProvider from "./_contexts/cart";

import Cart from "./_components/cart";

import AuthProvider from "./_providers/auth";
import ResponsivityAlert from "./_components/responsivity-alert";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <CartProvider>
            {children}

            <Cart />
          </CartProvider>
        </AuthProvider>

        <Toaster position="top-center" />
        <ResponsivityAlert />
      </body>
    </html>
  );
}
